version: '3'

services:
  scraping:
    build: ./server
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongo
    environment:
      - DATABASE=mongodb://root:password@mongo:27017/scraping?authSource=admin
    networks:
      - app-network
  
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-persistent:/data/db
    networks:
      - app-network

volumes:
  mongo-persistent:

networks:
  app-network:
    driver: bridge